### specific SUP settings (path, files)
KEYW:
    item_types: # itemType
        asset: 'Assets'
        anim: 'Action'
    assets_types:
        characters: Characters
        props: Props
    areaAssets: 
        text: Textures
        mod: Mod
        rig: Rig
    areaAnim:
        anim: Animation
        lay: Layout
        fx: VFX
    genericChar_na: genericChar

    item_thumbn_sufix: '_thumbnail.jpg'
    real_depot_fol_root: ''
    maped_depot_fol_root: ''
    local_fol_root: ''
Paths:
    ### itemType could be : Asset or Action
    ### assActType  could be : prop, char, set, anim, fx
    Rig_Ass_Path:        /{itemType}/{assActType}/{ass_na}/Maya/{areaAssRig}/{ass_na}_{areaAssRig}.ma
    Mod_Ass_Path:        /{itemType}/{assActType}/{ass_na}/Maya/{areaAssMod}/{ass_na}_{areaAssMod}.ma
    Ass_Thumb_Path:      /{itemType}/{assActType}/{ass_na}/{ass_na}_thumbnail.jpg
    
    RigTemplatePath:   /{itemType}/{assActType}/{genericChar_na}/Maya/{areaAssRig}/{genericChar_na}_{areaAssRig}.ma
    ModTemplatePath:   /{itemType}/{assActType}/{genericChar_na}/Maya/{areaAssMod}/{genericChar_na}_{areaAssMod}.ma

    Anim_Template:         /{itemType}/{assActType}/animTemplate/animTemplate.ma
    Anim_Path:            /{itemType}/{assActType}/{subpath}{anim_na}/{anim_na}_v000.ma
    Anim_Root:            /{itemType}/{assActType}/
    #Unreal_Anim_Root:     /{itemType}/Content/Sim/Characters/Generic/Art/Anim/

